// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_pier__best_time = "CgkIn575jYcQEAIQBg"; // <GPGSID>
        public const string leaderboard_bridge_climb__best_time = "CgkIn575jYcQEAIQAw"; // <GPGSID>
        public const string leaderboard_sky_fall__best_time = "CgkIn575jYcQEAIQBw"; // <GPGSID>
        public const string leaderboard_green_forest__best_time = "CgkIn575jYcQEAIQAQ"; // <GPGSID>
        public const string leaderboard_boxed_in__best_time = "CgkIn575jYcQEAIQAg"; // <GPGSID>
        public const string leaderboard_meadow__best_time = "CgkIn575jYcQEAIQBQ"; // <GPGSID>
        public const string leaderboard_the_peaks__best_time = "CgkIn575jYcQEAIQCQ"; // <GPGSID>
        public const string leaderboard_the_jump__best_time = "CgkIn575jYcQEAIQCA"; // <GPGSID>
        public const string leaderboard_the_woods__best_time = "CgkIn575jYcQEAIQCg"; // <GPGSID>
        public const string leaderboard_hill_race__best_time = "CgkIn575jYcQEAIQBA"; // <GPGSID>

}

